/**
* Copyright (C) 2016-present The ISLE Authors
*
* The isle-dashboard program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

// EXPORTS //

export const BUTTON_PAUSE = 'BUTTON_PAUSE';
export const BUTTON_RESUME = 'BUTTON_RESUME';
export const CALCULATOR_SOLVE = 'CALCULATOR_SOLVE';
export const DASHBOARD_CLICK_GENERATE = 'DASHBOARD_CLICK_GENERATE';
export const TABLE_FILTER = 'TABLE_FILTER';
export const TABLE_RESET = 'TABLE_RESET';
export const TABLE_SORT = 'TABLE_SORT';
export const USER_FEEDBACK_CONFUSED = 'USER_FEEDBACK_CONFUSED';
export const USER_FEEDBACK_UNDERSTOOD = 'USER_FEEDBACK_UNDERSTOOD';
export const USER_FEEDBACK_FORM = 'USER_FEEDBACK_FORM';
export const IMAGE_QUESTION_SUBMISSION = 'IMAGE_QUESTION_SUBMISSION';
export const IMAGE_QUESTION_OPEN_HINT = 'IMAGE_QUESTION_OPEN_HINT';
export const FILE_QUESTION_SUBMISSION = 'FILE_QUESTION_SUBMISSION';
export const FILE_QUESTION_OPEN_HINT = 'FILE_QUESTION_OPEN_HINT';
export const FREE_TEXT_QUESTION_SUBMIT_ANSWER = 'FREE_TEXT_QUESTION_SUBMIT_ANSWER';
export const FREE_TEXT_QUESTION_DISPLAY_SOLUTION = 'FREE_TEXT_QUESTION_DISPLAY_SOLUTION';
export const FREE_TEXT_QUESTION_OPEN_HINT = 'FREE_TEXT_QUESTION_OPEN_HINT';
export const TEXT_SURVEY_SUBMISSION = 'TEXT_SURVEY_SUBMISSION';
export const JSSHELL_DISPLAY_SOLUTION = 'JSSHELL_DISPLAY_SOLUTION';
export const JSSHELL_EVALUATION = 'JSSHELL_EVALUATION';
export const JSSHELL_OPEN_HINT = 'JSSHELL_OPEN_HINT';
export const LESSON_CONNECTED = 'LESSON_CONNECTED';
export const LESSON_SUBMIT = 'LESSON_SUBMIT';
export const LIKERT_SCALE_SUBMISSION = 'LIKERT_SCALE_SUBMISSION';
export const DATA_EXPLORER_CONTINGENCY_TABLE = 'DATA_EXPLORER_CONTINGENCY_TABLE';
export const DATA_EXPLORER_FREQUENCY_TABLE = 'DATA_EXPLORER_FREQUENCY_TABLE';
export const DATA_EXPLORER_SUMMARY_STATISTICS = 'DATA_EXPLORER_SUMMARY_STATISTICS';
export const DATA_EXPLORER_HISTOGRAM = 'DATA_EXPLORER_HISTOGRAM';
export const DATA_EXPLORER_BARCHART = 'DATA_EXPLORER_BARCHART';
export const DATA_EXPLORER_BOXPLOT = 'DATA_EXPLORER_BOXPLOT';
export const DATA_EXPLORER_CONTOURPLOT = 'DATA_EXPLORER_CONTOURPLOT';
export const DATA_EXPLORER_HEATMAP = 'DATA_EXPLORER_HEATMAP';
export const DATA_EXPLORER_INTERVALPLOT = 'DATA_EXPLORER_INTERVALPLOT';
export const DATA_EXPLORER_LINEPLOT = 'DATA_EXPLORER_LINEPLOT';
export const DATA_EXPLORER_MAP = 'DATA_EXPLORER_MAP';
export const DATA_EXPLORER_MOSAIC = 'DATA_EXPLORER_MOSAIC';
export const DATA_EXPLORER_PIECHART = 'DATA_EXPLORER_PIECHART';
export const DATA_EXPLORER_QQPLOT = 'DATA_EXPLORER_QQPLOT';
export const DATA_EXPLORER_SCATTERPLOT = 'DATA_EXPLORER_SCATTERPLOT';
export const DATA_EXPLORER_SPLOM = 'DATA_EXPLORER_SPLOM';
export const DATA_EXPLORER_VIOLINPLOT = 'DATA_EXPLORER_VIOLINPLOT';
export const DATA_EXPLORER_TESTS_ANOVA = 'DATA_EXPLORER_TESTS_ANOVA';
export const DATA_EXPLORER_TESTS_CHISQUARE = 'DATA_EXPLORER_TESTS_CHISQUARE';
export const DATA_EXPLORER_TESTS_CORRTEST = 'DATA_EXPLORER_TESTS_CORRTEST';
export const DATA_EXPLORER_TESTS_KRUSKAL = 'DATA_EXPLORER_TESTS_KRUSKAL';
export const DATA_EXPLORER_TESTS_PROPTEST = 'DATA_EXPLORER_TESTS_PROPTEST';
export const DATA_EXPLORER_TESTS_TWO_SAMPLE_PROPTEST = 'DATA_EXPLORER_TESTS_TWO_SAMPLE_PROPTEST';
export const DATA_EXPLORER_TESTS_TWO_SAMPLE_MEAN = 'DATA_EXPLORER_TESTS_TWO_SAMPLE_MEAN';
export const DATA_EXPLORER_TESTS_MEAN = 'DATA_EXPLORER_TESTS_MEAN';
export const DATA_EXPLORER_SHARE_HISTOGRAM = 'DATA_EXPLORER_SHARE_HISTOGRAM';
export const DATA_EXPLORER_SHARE_BARCHART = 'DATA_EXPLORER_SHARE_BARCHART';
export const DATA_EXPLORER_SHARE_BOXPLOT = 'DATA_EXPLORER_SHARE_BOXPLOT';
export const DATA_EXPLORER_SHARE_CONTOURPLOT = 'DATA_EXPLORER_SHARE_CONTOURPLOT';
export const DATA_EXPLORER_SHARE_HEATMAP = 'DATA_EXPLORER_SHARE_HEATMAP';
export const DATA_EXPLORER_SHARE_INTERVALPLOT = 'DATA_EXPLORER_SHARE_INTERVALPLOT';
export const DATA_EXPLORER_SHARE_LINEPLOT = 'DATA_EXPLORER_SHARE_LINEPLOT';
export const DATA_EXPLORER_SHARE_MAP = 'DATA_EXPLORER_SHARE_MAP';
export const DATA_EXPLORER_SHARE_MOSAIC = 'DATA_EXPLORER_SHARE_MOSAIC';
export const DATA_EXPLORER_SHARE_PIECHART = 'DATA_EXPLORER_SHARE_PIECHART';
export const DATA_EXPLORER_SHARE_QQPLOT = 'DATA_EXPLORER_SHARE_QQPLOT';
export const DATA_EXPLORER_SHARE_SCATTERPLOT = 'DATA_EXPLORER_SHARE_SCATTERPLOT';
export const DATA_EXPLORER_SHARE_SPLOM = 'DATA_EXPLORER_SHARE_SPLOM';
export const DATA_EXPLORER_SHARE_VIOLINPLOT = 'DATA_EXPLORER_SHARE_VIOLINPLOT';
export const DATA_EXPLORER_DECISION_TREE = 'DATA_EXPLORER_DECISION_TREE';
export const DATA_EXPLORER_HIERARCHICAL_CLUSTERING = 'DATA_EXPLORER_HIERARCHICAL_CLUSTERING';
export const DATA_EXPLORER_LASSO_REGRESSION = 'DATA_EXPLORER_LASSO_REGRESSION';
export const DATA_EXPLORER_LINEAR_REGRESSION = 'DATA_EXPLORER_LINEAR_REGRESSION';
export const DATA_EXPLORER_LOGISTIC_REGRESSION = 'DATA_EXPLORER_MULTIPLE_REGRESSION';
export const DATA_EXPLORER_MULTIPLE_REGRESSION = 'DATA_EXPLORER_MULTIPLE_REGRESSION';
export const DATA_EXPLORER_NAIVE_BAYES = 'DATA_EXPLORER_NAIVE_BAYES';
export const DATA_EXPLORER_PCA = 'DATA_EXPLORER_PCA';
export const DATA_EXPLORER_RANDOM_FOREST = 'DATA_EXPLORER_RANDOM_FOREST';
export const DATA_EXPLORER_KMEANS = 'DATA_EXPLORER_KMEANS';
export const DATA_EXPLORER_BIN_TRANSFORMER = 'DATA_EXPLORER_BIN_TRANSFORMER';
export const DATA_EXPLORER_CAT_TRANSFORMER = 'DATA_EXPLORER_CAT_TRANSFORMER';
export const DATA_EXPLORER_CLEAR_OUTPUT_PANE = 'DATA_EXPLORER_CLEAR_OUTPUT_PANE';
export const DATA_EXPLORER_DELETE_OUTPUT = 'DATA_EXPLORER_DELETE_OUTPUT';
export const DATA_EXPLORER_GROUP_TRANSFORMER = 'DATA_EXPLORER_GROUP_TRANSFORMER';
export const DATA_EXPLORER_RANDOM_TRANSFORMER = 'DATA_EXPLORER_RANDOM_TRANSFORMER';
export const DATA_EXPLORER_VARIABLE_TRANSFORMER = 'DATA_EXPLORER_VARIABLE_TRANSFORMER';
export const DATA_EXPLORER_DELETE_VARIABLE = 'DATA_EXPLORER_DELETE_VARIABLE';
export const DELETE_STICKY_NOTE = 'DELETE_STICKY_NOTE';
export const INSERT_STICKY_NOTE = 'INSERT_STICKY_NOTE';
export const EDITOR_RESET = 'EDITOR_RESET';
export const EDITOR_SAVE_PDF = 'EDITOR_SAVE_PDF';
export const EDITOR_SAVE_HTML = 'EDITOR_SAVE_HTML';
export const EDITOR_SUBMIT = 'EDITOR_SUBMIT';
export const ENGAGEMENT_SURVEY_START = 'ENGAGEMENT_SURVEY_START';
export const ENGAGEMENT_SURVEY_END = 'ENGAGEMENT_SURVEY_END';
export const IFRAME_INTERACTION = 'IFRAME_INTERACTION';
export const PLOT_DRAGGED = 'PLOT_DRAGGED';
export const MATCH_LIST_SUBMISSION = 'MATCH_LIST_SUBMISSION';
export const MATCH_LIST_TOGGLE_SOLUTION = 'MATCH_LIST_TOGGLE_SOLUTION';
export const MATCH_LIST_OPEN_HINT = 'MATCH_LIST_OPEN_HINT';
export const MULTIPLE_CHOICE_MATRIX_SUBMISSION = 'MULTIPLE_CHOICE_MATRIX_SUBMISSION';
export const MULTIPLE_CHOICE_OPEN_HINT = 'MULTIPLE_CHOICE_OPEN_HINT';
export const MULTIPLE_CHOICE_SUBMISSION = 'MULTIPLE_CHOICE_SUBMISSION';
export const MULTIPLE_CHOICE_SURVEY_SUBMISSION = 'MULTIPLE_CHOICE_SURVEY_SUBMISSION';
export const NUMBER_QUESTION_SUBMISSION = 'NUMBER_QUESTION_SUBMISSION';
export const NUMBER_QUESTION_OPEN_HINT = 'NUMBER_QUESTION_OPEN_HINT';
export const NUMBER_SURVEY_SUBMISSION = 'NUMBER_SURVEY_SUBMISSION';
export const ORDER_QUESTION_OPEN_HINT = 'ORDER_QUESTION_OPEN_HINT';
export const ORDER_QUESTION_SUBMISSION = 'ORDER_QUESTION_SUBMISSION';
export const OPEN_DOCUMENTATION = 'OPEN_DOCUMENTATION';
export const OPEN_LINK = 'OPEN_LINK';
export const PAGES_FIRST_PAGE = 'PAGES_FIRST_PAGE';
export const PAGES_NEXT_PAGE = 'PAGES_NEXT_PAGE';
export const PAGES_PREVIOUS_PAGE = 'PAGES_PREVIOUS_PAGE';
export const PAGES_LAST_PAGE = 'PAGES_LAST_PAGE';
export const PAGES_JUMP_PAGE = 'PAGES_JUMP_PAGE';
export const SHARE_ENGAGEMENT = 'SHARE_ENGAGEMENT';
export const SKETCHPAD_SAVE_PDF = 'SKETCHPAD_SAVE_PDF';
export const SKETCHPAD_SAVE_PNG = 'SKETCHPAD_SAVE_PNG';
export const SKETCHPAD_FIRST_PAGE = 'SKETCHPAD_FIRST_PAGE';
export const SKETCHPAD_NEXT_PAGE = 'SKETCHPAD_NEXT_PAGE';
export const SKETCHPAD_PREVIOUS_PAGE = 'SKETCHPAD_PREVIOUS_PAGE';
export const SKETCHPAD_LAST_PAGE = 'SKETCHPAD_LAST_PAGE';
export const SKETCHPAD_GOTO_PAGE = 'SKETCHPAD_GOTO_PAGE';
export const SKETCHPAD_INIT_PAGES = 'SKETCHPAD_INIT_PAGES';
export const SKETCHPAD_HIDE_POINTER = 'SKETCHPAD_HIDE_POINTER';
export const SKETCHPAD_HIDE_ZOOM = 'SKETCHPAD_HIDE_ZOOM';
export const SKETCHPAD_CLEAR_PAGE = 'SKETCHPAD_CLEAR_PAGE';
export const SKETCHPAD_CLEAR_ALL_PAGES = 'SKETCHPAD_CLEAR_ALL_PAGES';
export const SKETCHPAD_DRAW_CURVE = 'SKETCHPAD_DRAW_CURVE';
export const SKETCHPAD_DRAW_TEXT = 'SKETCHPAD_DRAW_TEXT';
export const SKETCHPAD_DRAG_ELEMENTS = 'SKETCHPAD_DRAG_ELEMENTS';
export const SKETCHPAD_INSERT_PAGE = 'SKETCHPAD_INSERT_PAGE';
export const SKETCHPAD_DELETE_ELEMENT = 'SKETCHPAD_DELETE_ELEMENT';
export const SKETCHPAD_VERTICAL_SCROLL = 'SKETCHPAD_VERTICAL_SCROLL';
export const SKETCHPAD_MOVE_POINTER = 'SKETCHPAD_MOVE_POINTER';
export const SKETCHPAD_MOVE_ZOOM = 'SKETCHPAD_MOVE_ZOOM';
export const STICKY_NOTE_TITLE = 'STICKY_NOTE_TITLE';
export const STICKY_NOTE_BODY = 'STICKY_NOTE_BODY';
export const STICKY_NOTE_MOVE = 'STICKY_NOTE_MOVE';
export const PLOT_UPDATE = 'PLOT_UPDATE';
export const PROPORTIONS_SURVEY_SUBMISSION = 'PROPORTIONS_SURVEY_SUBMISSION';
export const SEND_QUEUE_SIZE = 'SEND_QUEUE_SIZE';
export const ENTER_QUEUE = 'ENTER_QUEUE';
export const LEFT_QUEUE = 'LEFT_QUEUE';
export const QUESTION_CONFIDENCE = 'QUESTION_CONFIDENCE';
export const QUESTION_SKIPPED = 'QUESTION_SKIPPED';
export const QUIZ_FINISHED = 'QUIZ_FINISHED';
export const RSHELL_DISPLAY_SOLUTION = 'RSHELL_DISPLAY_SOLUTION';
export const RSHELL_EVALUATION = 'RSHELL_EVALUATION';
export const RSHELL_OPEN_HINT = 'RSHELL_OPEN_HINT';
export const RANGE_QUESTION_SUBMIT_ANSWER = 'RANGE_QUESTION_SUBMIT_ANSWER';
export const RANGE_QUESTION_OPEN_HINT = 'RANGE_QUESTION_OPEN_HINT';
export const RESPONSE_VISUALIZER_TOGGLE = 'RESPONSE_VISUALIZER_TOGGLE';
export const RESPONSE_VISUALIZER_EXTENDED = 'RESPONSE_VISUALIZER_EXTENDED';
export const REVEAL_CONTENT = 'REVEAL_CONTENT';
export const HIDE_CONTENT = 'HIDE_CONTENT';
export const SELECT_QUESTION_SUBMISSION = 'SELECT_QUESTION_SUBMISSION';
export const SELECT_QUESTION_MATRIX_SUBMISSION = 'SELECT_QUESTION_MATRIX_SUBMISSION';
export const START_SURVEY = 'START_SURVEY';
export const STOP_SURVEY = 'STOP_SURVEY';
export const TOGGLE_BLACKSCREEN = 'TOGGLE_BLACKSCREEN';
export const TOGGLE_PRESENTATION_MODE = 'TOGGLE_PRESENTATION_MODE';
export const USERS_ASSIGNED = 'USERS_ASSIGNED';
export const INDIVIDUAL_ASSIGNED = 'INDIVIDUAL_ASSIGNED';
export const ASSIGNMENT_CLEARED = 'ASSIGNMENT_CLEARED';
export const REMOVE_ASSIGNMENT = 'REMOVE_ASSIGNMENT';
export const VIDEO_PLAY = 'VIDEO_PLAY';
export const VIDEO_PAUSE = 'VIDEO_PAUSE';
export const VIDEO_START = 'VIDEO_START';
export const VIDEO_SEEK = 'VIDEO_SEEK';
export const VIDEO_END = 'VIDEO_END';
export const WIKIPEDIA_SEARCH = 'WIKIPEDIA_SEARCH';
export const GROUP_MODE_END = 'GROUP_MODE_END';
