version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 25
  ignore:
  - dependency-name: redux
    versions:
    - 4.1.0
  - dependency-name: webpack
    versions:
    - 5.34.0
    - 5.35.1
  - dependency-name: npm
    versions:
    - 7.10.0
    - 7.11.1
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.7.5
  - dependency-name: stylelint-config-standard
    versions:
    - 21.0.0
    - 22.0.0
  - dependency-name: node-pty
    versions:
    - 0.10.1
  - dependency-name: electron-store
    versions:
    - 8.0.0
  - dependency-name: node
    versions:
    - 15.12.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
  - dependency-name: electron
    versions:
    - 12.0.0
    - 12.0.4
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.2.4
  - dependency-name: eslint-plugin-testing-library
    versions:
    - 4.0.0
    - 4.0.1
    - 4.1.0
  - dependency-name: stemmer
    versions:
    - 2.0.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: react-select
    versions:
    - 4.1.0
    - 4.2.0
    - 4.2.1
    - 4.3.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.1
    - 4.0.0
  - dependency-name: react-json-tree
    versions:
    - 0.15.0
  - dependency-name: core-js
    versions:
    - 3.9.0
    - 3.9.1
  - dependency-name: semver
    versions:
    - 7.3.4
    - 7.3.5
  - dependency-name: whatwg-fetch
    versions:
    - 3.6.1
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.6
  - dependency-name: react-i18next
    versions:
    - 11.8.6
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: workbox-webpack-plugin
    versions:
    - 6.1.0
  - dependency-name: css-minimizer-webpack-plugin
    versions:
    - 2.0.0
  - dependency-name: "@babel/eslint-plugin"
    versions:
    - 7.13.15
  - dependency-name: ajv
    versions:
    - 8.0.5
    - 8.1.0
  - dependency-name: pdfjs-dist
    versions:
    - 2.7.570
  - dependency-name: d3
    versions:
    - 6.6.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
