export const MARKDOWN_CHANGED = 'MARKDOWN_CHANGED';
export const ENABLE_SCROLL_CHANGED = 'ENABLE_SCROLL_CHANGED';
export const TOGGLE_SCROLLING = 'TOGGLE_SCROLLING';
export const TOGGLE_TOOLBAR = 'TOGGLE_TOOLBAR';
export const FILE_LOADED = 'FILE_LOADED';
