name: Build

on:
  push:
    branches:
      - master
      - '**'

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
        cache: 'npm'
    - name: npm install & build
      run: |
        npm ci --legacy-peer-deps
        npm run build
      env:
        CI: true
    - name: npm lint & test
      run: |
        npm run lint
        npm test
      env:
        CI: true
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
        cache: 'npm'
    - name: npm install & build
      run: |
        npm ci --legacy-peer-deps
        npm run build
      env:
        CI: true
    - name: npm lint & test
      run: |
        npm run lint
        npm test
      env:
        CI: true
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
        cache: 'npm'
    - name: npm install & build
      run: |
        npm ci --legacy-peer-deps
        npm run build
      env:
        CI: true
    - name: npm lint & test
      run: |
        npm run lint
        npm test
      env:
        CI: true
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Calculate Test Coverage
      run: |
        npm ci --legacy-peer-deps
        npm run coverage
    - name: Upload Test Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

