name: Changelog

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  create_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Generate Changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        sinceTag: v0.57.0
        author: false
        issue: true,
        issuesWoLabels: false,
        pullRequests: false
        excludeTags: v0.60.0,v0.61.1,v0.65.0,v0.65.1,v0.74.1,v0.74.2,v0.75.4,v0.75.6
        excludeTagsRegex: ".*-[a-z]*\\.?\\d+"
        stripGeneratorNotice: true
        releaseUrl: https://github.com/isle-project/isle-editor/releases/tag/%s
    - name: Update Changelog
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -sam "Update Changelog"
        git push

