name: Package upon Release

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  package_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
    - name: npm install and package
      run: |
        npm ci --legacy-peer-deps
        npm run package-ci
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
  package_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
    - name: npm install and package
      continue-on-error: true
      run: |
        npm ci --legacy-peer-deps
        npm run package-ci
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
  package_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
    - name: npm install and package
      run: |
        npm ci --legacy-peer-deps
        npm run package-ci
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
